name: Terraform Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_checks:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">= 1.0.0"

      - name: TFLint
        run: tflint

      - name: Checkov
        run: checkov -d .

      - name: Terrascan
        run: terrascan

      - name: tfsec
        run: tfsec .

      # Additional steps can be added as needed for testing or deployment
