- name: run tflint
        id: tflint
        run: |
          tflint -f compact --recursive --force 2>&1 | tee tflint-out.txt
          if [ ! -s tflint-out.txt ]; then
            echo "TFLint run has no findings" >> tflint-out.txt
          else
            sed -i '1i*************' tflint-out.txt
            sed -i '1iTFLint Report' tflint-out.txt
          fi
      - name: TFLint Output in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: tflint-outputs
          recreate: true
          path: tflint-out.txt

      - name: Checkov Scan
        id: checkov_scan
        run: |
          mkdir reports
          checkov -d . --skip-path ./.github --skip-path ./test -s -o cli -o junitxml --output-file-path ./reports
      - name: Display Checkov Scan Report in Workflow
        id: checkov-scan-report
        uses: dorny/test-reporter@v1
        if: ${{ steps.checkov_scan.outcome == 'success' }}
        with:
          fail-on-error: false
          name: Checkov Scan Report
          path: ./reports/results_junitxml.xml
          reporter: java-junit

      - name: Publish Checkov Scan Report in PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: ./reports/results_junitxml.xml
          check_name: Checkov Scan Report
          fail_on: nothing
